### PR TITLE
Add disabled dates prop + update readme

### PR DESCRIPTION
**Pull request by valdoryu**

### CODE REVIEW

**Review by lusarz — CHANGES_REQUESTED** [review]
Good job. Would you like to add unit tests ?

**Comment by valdoryu** [comment]
@lusarz Sorry, I didn't have time to do it this week, I will write them this week end

**Comment by lusarz** [comment]
@ValdoGhafoor That's okay, take your time :)

**Comment by valdoryu** [comment]
@lusarz I finally added some tests :)

**Review by lusarz — APPROVED** [review]

**Pull request merged**
